. ~/ml-workspace/install/01-init-environment.sh
. ~/ml-workspace/install/02-init-package-install-build.sh
. ~/ml-workspace/install/03-install-system-tools.sh
. ~/ml-workspace/install/04-install-network-tools.sh
. ~/ml-workspace/install/05-install-terminal-tools.sh
. ~/ml-workspace/install/06-install-database-tools.sh
. ~/ml-workspace/install/07-install-version-control-systems.sh
. ~/ml-workspace/install/08-install-images-graph-tools.sh
. ~/ml-workspace/install/09-install-X11-extensions.sh
. ~/ml-workspace/install/10-install-protobuf-build-tools.sh
. ~/ml-workspace/install/11-install-compression-tools.sh
. ~/ml-workspace/install/12-instal-openssh-tools.sh
. ~/ml-workspace/install/13-install-container-entrypoint.sh
. ~/ml-workspace/install/14-install-openresty-web-gateway.sh
. ~/ml-workspace/install/15-install-miniconda-pip-python.sh
. ~/ml-workspace/install/16-install-nodejs-npm-typescript.sh
. ~/ml-workspace/install/17-install-dotnet-sdk.sh
. ~/ml-workspace/install/18-install-desktop-gui-vnc.sh
