apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-stack
  labels:
    app: lambda-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda-stack
  template:
    metadata:
      labels:
        app: lambda-stack
    spec:
      containers:
      - name: lambda-stack
        image: ghcr.io/wordslab-org/lambda-stack-cuda:0.1.13-22.04.2
        command:
          - "sleep"
          - "604800"
        ports:
        - containerPort: 8080
