apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-cuda
  labels:
    app: nvidia-cuda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-cuda
  template:
    metadata:
      labels:
        app: nvidia-cuda
    spec:
      containers:
      - name: nvidia-cuda
        image: nvidia/cuda:11.8.0-base-ubuntu22.04
        command:
          - "sleep"
          - "604800"
        ports:
        - containerPort: 8080
